# Path assoluto su dove salvare e caricare i modelli di machine learning
path: C:\Users\Danilo\Documents\Test

# Credenziali S3
s3_cred:
  username: REST
  password: Unimere$t01!

# Credenziali BasicAuth per l'uso delle API
server_cred:
  username: ml_rest
  password: mlRestCAU